name: Publish module

on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
      
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --name redis-test
          --ulimit nofile=1024:1024

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: npm ci --ignore-scripts=false

      - name: Security audit
        run: npm audit --audit-level=moderate --omit=dev

      - name: Lint check
        run: npm run lint

      - name: Spell check
        run: npm run spell

      - name: Unit tests
        run: npm test
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379

      - name: Build dist directory
        run: npm run build

      - name: Verify dist files
        run: |
          echo "Checking dist directory contents:"
          ls -la dist/
          echo "Verifying CommonJS build:"
          npm run test:cjs
          echo "Verifying ES Module build:"
          npm run test:esm

      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}